Added a basic scene with no controls and a skybox Adding default meshes to the scene creates this error as of now /home/dante/workspace/git/g3d/G3D10/data-files/shader/UniversalSurface/UniversalSurface_depthOnlyNonOpaque.pix(38) : error C0000: "This shader is intended for use with transparency" which occurs because of HAS_ALPHA=0 and HAS_TRANSPARENCY=0 one transparentObjects. This can be overriden in the Any file but I will try with opaque objects first by adding a custom ball and floor nodes.